### ISSUE TITLE
[Deprecated Version] : fancy_shimmer_image >=2.0.0 is forbidden for shimmer: ^3.0.0

### ISSUE THREAD

**Issue by BolisettySujith** [rodrigobastosv/fancy-shimmer-image#16]
Hy @rodrigobastosv,

When I was using this package I faced this issue saying the current version is deprecated, it seems like the newest version of [Shimmer](https://pub.dev/packages/shimmer) is ^3.0.0, and you are using ^2.0.0.

```
Because fancy_shimmer_image >=2.0.0 depends on shimmer ^2.0.0 and <project-name> depends on shimmer ^3.0.0, fancy_shimmer_image >=2.0.0 is forbidden.
So, because <project-name> depends on fancy_shimmer_image ^2.0.2, version solving failed.
pub get failed
command: "/home/sujith/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/home/sujith/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/home/sujith/.pub-cache",
}
exit code: 1
```

I can also help by contributing to this issue for fixing it...

**Comment by rodrigobastosv** [comment]
Hey @BolisettySujith , thanks a lot for using this package!

I just updated both the CachedNetworkImage and the Shimmer versions. We already have a new version on pub.dev.

Thanks a lot!
