### ISSUE TITLE
Cannot make shimmer shape circular

### ISSUE THREAD

**Issue by iamprafful** [rodrigobastosv/fancy-shimmer-image#5]
Tried using:
BoxDecoration & CircularAvtar 
```
    Container(
      decoration: BoxDecoration(shape: BoxShape.circle),
      margin: EdgeInsets.all(12.0),
      child: FancyShimmerImage(
        imageUrl: business[index].imgUrl,
        height: 90.0,
        width: 90.0,
        boxFit: BoxFit.fitHeight,
      ),
    );

```
and almost all ways to make the widget circular but still cannot make shimmer circular.

**Comment by rodrigobastosv** [comment]
Hi @prafful98 , sorry for the delay. Ill take a look at this today

**Comment by iamprafful** [comment]
Any Solution @rodrigobastosv

**Comment by rodrigobastosv** [comment]
Hi @prafful98 , i have been so busy, so sorry for that.

I add the possibility to pass your own BoxDecoration, and it will be used for the shimmer (only with you pass one).

You can for example pass:
```
boxDecoration: BoxDecoration(
    shape: BoxShape.circle,
    color: Colors.grey,
),
```
For your `FancyShimmerImage` and it will have circle shimmers :).

Just upgrade for version 1.0.2 of fancy_shimmer_image and you will be good to go

Hit me back with some feedback if it worked and thanks for using my package.

**Comment by rodrigobastosv** [comment]
Closing for now since the issue is fixed, but feel free to reopen if you want.
