### ISSUE TITLE
duration is not working 

### ISSUE THREAD

**Issue by Sreejithtechno** [rodrigobastosv/fancy-shimmer-image#6]
duration is not working

**Comment by rodrigobastosv** [comment]
Will take a look at it today

**Comment by rodrigobastosv** [comment]
Hi @Sreejithtechno, sorry for the delay to give you an answer, i have been busy.

Duration will only be counted until the image is not loaded yet, as soon as your image loads the shimmer will disapear.

For example, if you set the duration to 5 seconds and the image loads in 2 seconds, the shimmer will NOT go on for 3 more seconds.

I'm pretty sure this is the desired behavior. Do you have any use case that makes sense for you?

**Comment by rodrigobastosv** [comment]
Closing for now but feel free to reopen if need more help
