### ISSUE TITLE
Image not showing up

### ISSUE THREAD

**Issue by patsanch** [rodrigobastosv/fancy-shimmer-image#8]
Hi,

I tried the example code and the shimmer works, but no image is displayed. I tried different image urls and still can't make it show up. Am I missing anything?

Thanks!

**Comment by rodrigobastosv** [comment]
Hi @patsanch , thanks for using this package =)

Everything is working fine for me. What version are you using? Maybe you are offline?

**Comment by patsanch** [comment]
Hi,

Happy to try it out. It's working now. You're right. It was probably my connection. I see the shimmer now and it fades as soon as the image shows up.

Thanks!

**Comment by rodrigobastosv** [comment]
Nice to hear @patsanch!

Thanks!
