### ISSUE TITLE
Images in the readme file not visible

### ISSUE THREAD

**Issue by RomaPai** [rodrigobastosv/fancy-shimmer-image#9]
It shows up "enter image description here". It would be really helpful if you could place the GIF of the required result this package produces.

**Comment by rodrigovasconceloszup** [comment]
Hi @RomaPai , thanks for using this package.

The link is broken, i will upload the gifs again and update the readme.

Thanks very much

**Comment by rodrigobastosv** [comment]
Hey @RomaPai i've just updated the readme to point to new working gifs.

Thanks a lot for pointing this and this again for using this package.
